---
swagger: "2.0"
info:
  x-ibm-name: "sample-inventory-api"
  title: "iib inventory api"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/iib-inventory-api"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /item/{id}:
    parameters:
    - name: "id"
      type: "string"
      required: true
      in: "path"
    get:
      responses:
        200:
          description: "200 OK"
          schema:
            $ref: "#/definitions/item"
      operationId: "getId"
    put:
      responses:
        200:
          description: "200 OK"
          schema:
            $ref: "#/definitions/item"
      operationId: "putId"
      parameters:
      - name: "item"
        required: true
        in: "body"
        schema:
          $ref: "#/definitions/item"
    delete:
      responses:
        200:
          description: "200 OK"
          schema:
            type: "string"
      operationId: "deleteId"
      parameters:
      - name: "id"
        type: "integer"
        required: true
        in: "path"
        format: "int32"
  /items:
    get:
      responses:
        200:
          description: "200 OK"
          $ref: "#/definitions/items"
          schema:
            $ref: "#/definitions/items"
      operationId: "getItems"
    post:
      responses:
        200:
          description: "200 OK"
          schema:
            $ref: "#/definitions/items"
      operationId: "postItems"
      parameters:
      - name: "body"
        required: false
        in: "body"
        schema:
          $ref: "#/definitions/items"
        description: "{\"id\":999,\"name\":\"item999\",\"description\":\"\",\"price\"\
          :999.99}"
definitions:
  item:
    properties:
      itemId:
        type: "integer"
        description: "unique id"
        format: "int32"
      name:
        type: "string"
        description: "item's name"
      description:
        type: "string"
      price:
        type: "number"
        description: "item's price"
        format: "float"
      imgAlt:
        type: "string"
      img:
        type: "string"
      quantity:
        type: "integer"
        format: "int32"
    additionalProperties: false
    required:
    - "price"
    - "itemId"
  items:
    type: "array"
    items:
      $ref: "#/definitions/item"
tags: []
